server:
  port: 6677
  
spring: 
  application:  
    name: wwg-microservice-api-gateway #指定服务名
    
logging: 
  level:
    org.springframework: DEBUG


eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://wwg:wwg123@127.0.0.1:6868/eureka/
  instance: 
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1 #指定服务ip地址
    instance-id: ${spring.application.name}:${server.port} #指定实例id
    
zuul: 
  routes: 
#    item-service: #item-service这个名字是任意写的
#      path: /item-service/** #配置请求URL的请求规则
#      url: http://127.0.0.1:8081 #真正的微服务地址    面向服务配置，不破坏Hystrix、Ribbon特性
#      serviceId: wwg-microservice-item #指定Eureka注册中心中的服务id
    wwg-microservice-item: /item-service/**   #替代path和serviceId的功能的简化配置
  # 忽略以下服务列表
#  ignored-services: wwg-microservice-eureka
  # 忽略所有服务列表
#  ignored-services: '*'
#  ignored-patterns: /**/admin/**   #忽略所有包含admin的
  
  
  