logging:
  config: classpath:config/logback-spring.xml
  # 日志路径  ./logs /var/log/${spring.application.name}
  path: ./logs
  # 分割文件设置 超过 100MB就进行分割，最大保留历史 90天
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
       # 自己工程下命名的类的日志级别
    cn.wwg.microservice: DEBUG
   
spring: 
  application:  
    name: wwg-microservice-item #指定服务名    
eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://wwg:wwg123@127.0.0.1:6868/eureka/
  instance: 
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1 #指定服务ip地址
    instance-id: ${spring.application.name}:${server.port} #指定实例id
    
#在配置让config_client动态加载配置文件的时候设置的。    
management:
  security:
    enabled: false #是否开启actuator安全认证