server:
  port: 6688 #服务端口

spring: 
  application:  
    name: wwg-microservice-config-server #指定服务名
  cloud:  
    config:
      server:
        git: #配置git仓库地址
          uri: http://192.168.2.139:10080/codelearner1024/wwg-config-server.git
          username: codelearner1024
          password: wwg123456
  rabbitmq: #RabbitMQ相关的配置
    host: 127.0.0.1
    # 默认端口
    port: 5672
    # 默认账号密码
    username: guest
    password: guest
eureka: 
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://wwg:wwg123@127.0.0.1:6868/eureka/
  instance: 
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ipAddress: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id
management:
  security:
    enabled: false #是否开启actuator安全认证